### ISSUE TITLE
Add a Delete All button

### ISSUE THREAD

**Issue by Gitoffthelawn** [ettoolong/TextareaCache#17]
Add a button to delete everything in TACL's storage.

**Comment by wildskyf** [comment]
Cool, thank you for this suggestion!

**Comment by Gitoffthelawn** [comment]
You're welcome!

**Comment by wildskyf** [comment]
It should work in the latest version!

**Comment by Gitoffthelawn** [comment]
It works!  Thank you!

At first, I thought it would be best to place it to the right of the *Delete* button, but I've grown to like it where it is.
