### ISSUE TITLE
Date of all items is off by a month

### ISSUE THREAD

**Issue by Gitoffthelawn** [ettoolong/TextareaCache#19]
The date of all the entries is off by a month.  Hopefully an easy fix!

**Comment by Gitoffthelawn** [comment]
@wildskyf Any thoughts on this?

**Comment by wildskyf** [comment]
@Gitoffthelawn I don't get your point. :/

Can you provide some examples or more-detailed description?

Thank you for your patient... I am really busy recently...

**Comment by Gitoffthelawn** [comment]
If today is 2017/06/08, and the extension saves an entry, it will save it with a date of 2017/5/8.

Every entry is off by exactly one month.

**Comment by wildskyf** [comment]
Oh... I got you !!!
It is really a idiot mistake. Orz

It will be fixed in the next version. !!!

**Comment by Gitoffthelawn** [comment]
LOL :)
