### ISSUE TITLE
Textarea Cache Lite 1.0.3 doesn't work under Nightly Fx54

### ISSUE THREAD

**Issue by streetwolf** [ettoolong/TextareaCache#2]
Running on Windows 10 Pro 64 bit with Nightly 64 bit.  When clicking the TCL icon all that is produced is an arrow under the icon.  I've seen this before with another WebExtension add-on and it was cause by me setting the pref 'apz.allow_zooming'  to true.  The default is false.  However in this case the pref is false so it appears not to be the same cause.

**Comment by wildskyf** [comment]
![tcl](https://cloud.githubusercontent.com/assets/6042803/23217671/0af43242-f955-11e6-9fe3-e9bd63e83309.png)

**Comment by streetwolf** [comment]
If you can't test on a Windows 10 system we can use TeamViewer to let you on my system remotely to do some debugging.

**Comment by wildskyf** [comment]
Oh, you are so nice!
Which timezone do you live in?

WS

2017年2月24日 04:36，"Gary" <notifications@github.com>寫道：

**Comment by streetwolf** [comment]
UTC -5 east coast of USA.

Btw... the new version 1.1.0 doesn't show the icon at all.

**Comment by wildskyf** [comment]
I have changed it from browserAction to pageAction, which allow it appear
when there is at least one textarea in current page. You could try it in
http://ettoolong.github.io/test/textarea.html , and tcl will appear at the
left position of reload icon(like attached file).

WS


​


<http://wildsky.cc>----------
Wildsky Fann
@wildskyf

**Comment by wildskyf** [comment]
I have changed it from browserAction to pageAction, which allow it appear
when there is at least one textarea in current page. You could try it in
http://ettoolong.github.io/test/textarea.html , and tcl will appear at the
left position of reload icon(like image below).

WS

![2017-02-24 10 39 00](https://cloud.githubusercontent.com/assets/6042803/23288321/d798724e-fa7d-11e6-9e45-21cd98c1838b.png)



----------
Wildsky Fann
@wildskyf

**Comment by streetwolf** [comment]
1.1.2 now shows the contents of the cache.  Well done.  Are you going to try and make TCL more like TC?  I'm sure you know a few things are missing to make it a keeper.

**Comment by wildskyf** [comment]
Of course.
I am currently trying to make TCL save data from WYSIWYG editor.

Hey, Gary, so TCL is working on your Firefox now, right? If it is so, let's close this issued? And open another issue for each feature request.
