### ISSUE TITLE
No icon in the navigate bar

### ISSUE THREAD

**Issue by xerces8** [ettoolong/TextareaCache#20]
The description says "If there is any textarea or WYSIWYG editor in the website you are browsing, you would find that there is an icon at the left of reload icon in the navigate bar."

But there is no icon in my bar. The toolbar icon is present and it works. Just no icon in the navigation bar.

I have Firefox 53.0.3 on Windows 7 and Textarea Cache Lite 2.2.5

**Comment by wildskyf** [comment]
Sorry about that. It is my mistake.
Icon in navigation bar is old feature, and I forgot to change it.
It will be back when I solve issue #15 
But I got a little busy recently... So please wait for me.

**Comment by wildskyf** [comment]
sorry, I made a mistake in 2.2.7, which caused this bug is still there...
It will be fixed in 2.2.8.
