### ISSUE TITLE
Firefox 55+ and checkboxes

### ISSUE THREAD

**Issue by rayman89** [ettoolong/TextareaCache#23]
Firefox 55 does not show checkboxes for most webextensions this includes textarea cache lite.

**Comment by wildskyf** [comment]
Could you please add more detail or add some screenshots for your report?

**Comment by rayman89** [comment]
When you go to the options of the addon if the addon has checkboxes there in firefox 55+ those checkboxes do not show up.

![imagen](https://user-images.githubusercontent.com/5449042/27555731-768a96ac-5a78-11e7-9cdf-ad14bdef26af.png)

**Comment by wildskyf** [comment]
Got you, I will fix it before v55.0 releasing.
Thank you!

**Comment by wildskyf** [comment]
hi @rayman89 ,

I just install ff v55.0b13 , and go to option page of TCL
The checkbox is there safe and sound. like this

![screenshot from 2017-08-05 11-52-55](https://user-images.githubusercontent.com/6042803/28992647-a6a4c97c-79d4-11e7-96eb-bd61471af071.png)

Could you confirm whether this problem still happen or not? if it is, please provide the OS version for me (Win7, macOS Sierra, ... etc) thank you :)

**Comment by rayman89** [comment]
Checkboxes are showing now probably firefox fixed it.
