### ISSUE TITLE
Use FILO instead of FIFO

### ISSUE THREAD

**Issue by Gitoffthelawn** [ettoolong/TextareaCache#25]
Show most recently cached data by default instead of least recently cached data.

**Comment by wildskyf** [comment]
@Gitoffthelawn  thanks, it will happen at 2.3.0 :)

**Comment by wildskyf** [comment]
I found this issue is duplicate with #22 , so let's move the progress tracking there. :)

**Comment by Gitoffthelawn** [comment]
Great!  Thanks!
