### ISSUE TITLE
Drop list entries get truncated if TACL icon is on left end of toolbar

### ISSUE THREAD

**Issue by bendover22** [ettoolong/TextareaCache#26]
My suggestion here may be somewhat related to issue [https://github.com/ettoolong/TextareaCache/issues/11](url) - but not exactly.

Would it be possible to show part or all of the URL or site name with each entry?
1) Maybe in a tooltip style, when hover entries that are truncated in the drop list?
2) Also, because some TACL drop list entries include (some) of the site's name.  Other entries don't show any of the site name.

* If TACL's icon is placed on **left side** of bookmarks toolbar or URL bar, then the drop list has plenty of room, as it then expands to the right of the icon.

* Another part of a solution would be when TACL's icon is at the right side of the screen, have the saved entries container expand as far to the left, as it expands when the icon is on the screen's left side.  

That doesn't solve the issue of some entries currently not including a site name or URL.

![text area cache lite2 3_drop list truncates entries](https://user-images.githubusercontent.com/1909407/28999066-00adf076-7a00-11e7-86bc-21bb3c0d0ce6.jpg)

**Comment by wildskyf** [comment]
Hi @bendover22 ,


I have make some change in ba390de.
Here is the preview of it:
![21844038_1923759307639289_1243433519_o](https://user-images.githubusercontent.com/6042803/30513422-73dee6a8-9b35-11e7-9513-a4b4fdb060ca.jpg)


you could see the whole url titile when you hover on items in drop-down selector. ( yeah tooltips :D )

btw, I also hide the serial number in the end of website title. I think it it not important for users.

Will this solve your problem? This will happen in v2.3.3.
