### ISSUE TITLE
Change tooltip label when hover TACL icon

### ISSUE THREAD

**Issue by bendover22** [ettoolong/TextareaCache#27]
The TACL toolbar icon isn't very distinctive (most aren't).  When hovered, it just shows "Save your data."  Hovering or clicking the icon doesn't save anything.   

When hovering it, a menu could pop up - like many addons & apps.
Or at least show the name, or "view TextArea Cache entries," or such.

**Comment by wildskyf** [comment]
Good Suggestion! I will change it in the next version. :)
Thank you!
