### ISSUE TITLE
Will not install on Android Fx55

### ISSUE THREAD

**Issue by revad** [ettoolong/TextareaCache#32]
Claims to work with Fx Android (v2.3.3). Will not install in Fx 55 Android. No messages.

**Comment by wildskyf** [comment]
Hi @revad 
This add-on is not compatible with Firefox for Android now.

**Comment by revad** [comment]
Then you need to change compatibility data on AMO. It says:
"Released September 16, 2017 19.8 KiB Works with Firefox for Android 51.0 - *, Firefox 51.0 and later "

BTW: an Android version is more required than a desktop version.
