### ISSUE TITLE
Difference between TextareaCache and TextareaCache Lite?

### ISSUE THREAD

**Issue by Gitoffthelawn** [ettoolong/TextareaCache#5]
Can you explain the difference between TextareaCache and TextareaCache Lite?

Might be useful info for the README and the AMO description too.

**Comment by Offerel** [comment]
Would be cool to have some explanation. thx

**Comment by ettoolong** [comment]
The author of TC(Hemiola SUN) was stopped maintain it. TC is a legacy extension base-on XUL overlay that will stop support after Firefox 57 (the end of 2017).

[wildsky](https://github.com/wildskyf) carated an new add-on TCL to re-implement main features of TC. If the feature you need are not support yet, waitting for update. If all the features you need are already support by TCL, you can switch to TCL and start use it.

Finally, TCL will support most of features and update continuously. Install TCL and test it, please feel free to give us your feedback, thanks.

**Comment by Gitoffthelawn** [comment]
@ettoolong Thank you!

So this is a WebExtensions implementation of TC, correct?

If you would like me to write a good explanation for AMO for you to post, just ask, and I will be happy to do it for you.

**Comment by ettoolong** [comment]
Yes, TCL is base-on WebExtension APIs.
